apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    env: web
spec:
  replicas: 3
  selector:
    matchLabels:
      env: web
  template:
    metadata:
      name: mynginx
      labels:
        env: web
    spec:
      containers:
      - name: mynginx
        image: nginx